refactor: convert pageScript to typeScript
NethermindEth/blink-extension pull request #5
Opened 2024-07-29 19:19 UTC by Benjtalkshow

#2 
Draft, still refactoring

2024-08-07 09:08 UTC, jelilat requested changes
Hi @Benjtalkshow 

Thanks for your contribution. Kindly make the changes requested and it should be gtm

2024-08-07 09:08 UTC, jelilat commented on package-lock.json
Remove this file and use yarn instead

2024-08-07 09:08 UTC, jelilat commented on src/pageScript.ts
>  import { parseTransaction } from 'viem';
```suggestion
import { parseTransaction, Address } from 'viem';
```

Import Address from viem and use that as a type instead of `0x${string}`

2024-08-07 09:08 UTC, jelilat commented on src/pageScript.ts
> +    sign: async (serializedTx: `0x${string}`) => {
```suggestion
    sign: async (serializedTx: Address) => {
```

2024-08-07 09:08 UTC, jelilat commented on src/pageScript.ts
> +        to: tx.to as `0x${string}`,
```suggestion
        to: tx.to as Address,
```

2024-08-07 09:08 UTC, jelilat commented on src/pageScript.ts
> +  SIGN_TRANSACTION_ETHEREUM: async (data: { transaction: `0x${string}` }) => {
```suggestion
  SIGN_TRANSACTION_ETHEREUM: async (data: { transaction: Address }) => {
```

2024-08-07 09:08 UTC, jelilat commented on src/pageScript.ts
> +let connectedAddress: string = "";
```suggestion
let connectedAddress: Address = "";
```

2024-08-07 18:39 UTC, Benjtalkshow commented
@jelilat ,
I have made the changes please review my PR

2024-08-12 15:11 UTC, jelilat commented
Thanks for your contribution @Benjtalkshow 

There, however, were some conflicts and a few issues with the implementation so I had to fix them. You can check https://github.com/NethermindEth/blink-extension/commit/0c97c97b364299ae8b3c1776476d9fdbf4f5ee51 for the fix

2024-08-12 15:11 UTC, closed without merging